esphome:
  name: the-feeder
  friendly_name: The-feeder

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Pdjd/wKG9aedE+/E4d/tOjRF1ZetFnO7hkmDkTtvqbs="

ota:
  password: "22a83544448d9d715901a1ca77df245b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    

# Example output platform
# On ESP32, use ledc output
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: 0
    frequency: 50 Hz

light:
  - platform: monochromatic
    name: "Кормушка"
    output: pwm_output