esphome:
  name: the-collar
  friendly_name: The-collar

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FvneVqjuAOJz5wmcflVvNxjaNr/jd3j23csoCK8jm68="

ota:
  password: "25b8500a8f9a8028b08f6a00abc0f241"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal 
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 3s
    entity_category: "diagnostic"

  - platform: copy # 
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    name: "Ошейник"

light:
  - platform: status_led
    name: "led"
    pin: 2